# Generated by Django 6.0.7 on 2026-08-25 08:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('triage', '0004_remove_businesscase_directorate_and_more'),
        ('triage', '0005_businesscase_status_enum'),
    ]

    operations = [
    ]
