# Generated by Django 6.0.7 on 2026-09-23 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('triage', '0006_businesscaseresponse_businesscaseresponsesection_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='businesscaseresponse',
            old_name='business_case_id',
            new_name='business_case',
        ),
        migrations.RenameField(
            model_name='businesscaseresponseblock',
            old_name='business_case_response_section_id',
            new_name='business_case_response_section',
        ),
        migrations.RenameField(
            model_name='businesscaseresponsesection',
            old_name='business_case_response_id',
            new_name='business_case_response',
        ),
        migrations.RenameField(
            model_name='businesscaseresponsesummary',
            old_name='business_case_response_id',
            new_name='business_case_response',
        ),
        migrations.AlterField(
            model_name='businesscaseresponse',
            name='status',
            field=models.TextField(choices=[('Pending', 'Pending'), ('Completed', 'Completed'), ('Error', 'Error')], default='Pending'),
        ),
    ]
