# Generated by Django 6.0.7 on 2026-09-23 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('triage', '0007_rename_business_case_id_businesscaseresponse_business_case_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='businesscaseresponse',
            name='original_filename',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='businesscaseresponse',
            name='s3_key',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
